### ISSUE TITLE
question about run preprocess.py on metaqa

### ISSUE THREAD

**Issue by DW934** [Flitternie/GraphQ_IR#13]
When I run the preprocess.py on dataset meatqa,I get the following error:

Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\ChatKBQA\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\anaconda3\envs\ChatKBQA\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Code\GraphQ_IR-master\preprocess.py", line 98, in <module>
    main()
  File "C:\Code\GraphQ_IR-master\preprocess.py", line 90, in main
    outputs = encode_dataset(dataset, vocab, tokenizer)
  File "C:\Code\GraphQ_IR-master\preprocess.py", line 20, in encode_dataset
    inputs.append(item['input'])
KeyError: 'input'

Could you give me some clue about how this happen and how to fix it ?Thanks a lot!

**Comment by Flitternie** [comment]
It looks like there is a problem with the input format. Have you tried to make sure "input" is a valid key in MetaQA's input dataset?
